spring:
  application:
    name: JAMMIT_BE
  lifecycle:
    timeout-per-shutdown-phase: 120

  datasource:
    url: ENC(y+8EW09dhqnbVKvBHvelaPzeqVEt7Pqfi2Dd2gh3keDLSLHRzZszwgkTw4VJC9lpMupiVSECnaLmFTwt3Y2PbOanFn8+GfGqRb15UT1VjUCTsMbg76A2hz3f+EGvgeFSrMHeEAZSnP8=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(fwmMfrdwx6T/oH1EauIgiFPB5t8mhee7)
    password: ENC(Mrza5y969J5MB41EDouk/kE2ED/7J35X)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace    # Hibernate 바인딩 정보
    org.hibernate.stat: off               # Hibernate 통계 정보
    org.springframework.transaction: off  # 트랜잭션 디버깅

jwt:
  expiredAccessTokenMs: 86400000
  expiredRefreshTokenMs: 86400000
  secretKey: ENC(lh1kMo8tAKIdFO/qo3/D3uZY45ZGJ5W+OFTFjY8in/9LJR+Qs0QyV0S6FL1zFFznYPmoCLZcx2U=)

## Jasypt
jasypt:
  encryptor:
    key: ${jasypt_key}

server:
  shutdown: graceful
  port: 8083
