spring:
  application:
    name: JAMMIT_BE
  lifecycle:
    timeout-per-shutdown-phase: 120

  datasource:
    url: jdbc:mysql://localhost:3306/jammit
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hong
    password: zxcv1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace    # Hibernate 바인딩 정보
    org.hibernate.stat: off               # Hibernate 통계 정보
    org.springframework.transaction: off  # 트랜잭션 디버깅

jwt:
  expiredAccessTokenMs: 86400000
  expiredRefreshTokenMs: 86400000
  secretKey: ENC(lh1kMo8tAKIdFO/qo3/D3uZY45ZGJ5W+OFTFjY8in/9LJR+Qs0QyV0S6FL1zFFznYPmoCLZcx2U=)

## Jasypt
jasypt:
  encryptor:
    key: ${jasypt_key}

server:
  shutdown: graceful
  port: 8083

# S3
cloud:
  aws:
    credentials:
      access-key: ENC(QtldJ/h2U1UGb0Zfmf2RkggGD08nRsPcQxkSF2+xyhE=)
      secret-key: ENC(ZtjaK/1Tb791Ju8ay/v5NSMSH5fmupELDujmeestR+BGOSwRLhB0sVtfRMmRmknXwF/zrgmvP58=)
    region:
      static: ENC(x6/uuqcHpKqcLwYSWMfOZtRPHXBGSejO)
    s3:
      bucket: ENC(5RyziorhkYWj9Zxqxt3Ykg==)